#:schema node_modules/wrangler/config-schema.json
name = "sublink-worker"
main = "src/worker.jsx"
compatibility_date = "2024-07-24"
compatibility_flags = ["nodejs_compat"]

kv_namespaces = [
  { binding = "SUBLINK_KV", id = "d628d4b6f0504f21a4bf7707bec7ca5c" }
]

[assets]
directory = "./public"
